service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:us-east-1:200853450981:table/NBAPlayerData"
functions:
  graphql:
    handler: server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET